### ISSUE TITLE
why this instead of microtime?

### ISSUE THREAD

**Issue by brunobriante** [edbizarro/timer#1]
not trying too put this down but microtime is built-in, don't skew results (as this project spend some time instantiating itself) and can't measure timers with less than 1 second if the documentation is showing all units it can use.

**Comment by edbizarro** [comment]
yeah, use microtime(true) could be a better approach, I'm using Carbon just because fit my current need, but I'll give a look and rewrite to use microtime and basic math to return all the metrics (include duration)

**Comment by edbizarro** [comment]
Done!
